
[ems]
server = '10.10.11.3'               # Server address or address:port
current = '{"_id": "emskey"}'       # EMS parameters for current provisioning
ip = '(eth0)'                       # Public IP address of appliance - use "(<ifname>)" for selecting the first address of interface <ifname> automatically.
macid = '(eth0)'                    # MAC address of external interface -  use "(<ifname>)" for using the MAC address of <ifname> automatically.

[users]                             # User configuration

# Creates user "admin" with the provided parameters as an inner table
admin = { name = "Administrator", password = "sangoma", email = "admin@localhost" }

dummy = "sangoma"                   # Create user "dummy" with password "sangoma"
root = false                        # Disable the root user

# Valid fields for "users" inner tables:
#
#  name, email, ssh-publickey - String values
#  access, sudoer, ssh-enable - Boolean values (true/false)

[notifier]                          # Notification system configuration
check = true                        # Shows warning box if notification is disabled
enable = true                       # Enable the notification system
smtp-server = "127.0.0.1"           # SMTP server where to send notifications
smtp-port = 25                      # SMTP port for contacting server
smtp-user = "user"                  # Username for SMTP server
smtp-password = "pass"              # Password for SMTP server

[["eth0"]]                          # INTERFACE[.VLANID] This is LAN Port and VLAN settings. SBC will create it if it does not exist.
type="static4"                      # The protocol family type and which boot-time protocol should be used. Values are static4, dhcp4, static6, dhcp6, slaac6
address="10.10.10.2/24"             # IP address and network prefix.

[["eth0"]]                          # INTERFACE[.VLANID] This is LAN Port and VLAN settings. SBC will create it if it does not exist.
type="slaac6"                       # The protocol family type and which boot-time protocol should be used. Values are static4, dhcp4, static6, dhcp6, slaac6
hostname="sbc.ooredoo.local"        # Use this option for the DHCP server requires the client to specify a hostname before receiving an IP address. This parameter may not be required for static IP address.

# Interface Port 2 to be used to connect Customer network. By default they are DHCP. Onsite engineer can provision them fixed IP as well.

[["eth1"]]                          # INTERFACE[.VLANID] This is LAN Port and VLAN settings. SBC will create it if it does not exist.
type="dhcp4"                        # The protocol family type and which boot-time protocol should be used. Values are static4, dhcp4, static6, dhcp6, slaac6
hostname="sip.ooredoo.local"        # Use this option for the DHCP server requires the client to specify a hostname before receiving an IP address. This parameter may not be required for static IP address.
use_auto_dns="true"                 # Use the DNS servers returns from DHCP server. Values are true or false
persistant_dhcp="true"              # Keep retrying to get a DHCP lease indefinitely. Values are true or false

[["eth1"]]                          # INTERFACE[.VLANID] This is LAN Port and VLAN settings. SBC will create it if it does not exist.
type="dhcp6"                        # The protocol family type and which boot-time protocol should be used. Values are static4, dhcp4, static6, dhcp6, slaac6
hostname="sip.ooredoo.local"        # Use this option for the DHCP server requires the client to specify a hostname before receiving an IP address. This parameter may not be required for static IP address.
use_auto_dns="true"                 # Use the DNS servers returns from DHCP server. Values are true or false
persistant_dhcp="true"              # Keep retrying to get a DHCP lease indefinitely. Values are true or false

# Interface Port 3 to be used to connect EMS/OAM/SSW/Core network of Ooredoo. Two vlans on same ethernet cable. One for EMS and another for SIP Trunks.

[["eth2.80"]]                       # INTERFACE[.VLANID] This is LAN Port and VLAN settings. SBC will create it if it does not exist.
type="static4"                      # The protocol family type and which boot-time protocol should be used. Values are static4, dhcp4, static6, dhcp6, slaac6
address="192.168.10.6/30"           # IP address and network prefix.

"route.EMS" = { addr = "192.168.10.0/30", via = "192.168.10.5" } # route 1. Static routes through this interface. Format is: "route.name={ addr = destination/prefix, via = gateway }"
"route.OAM" = { addr = "172.16.0.0/16", via = "192.168.10.5" }   # route 2. Static routes through this interface. Format is: "route.name={ addr = destination/prefix, via = gateway }"

# Binds SIP profile PROFILE1 to this IP address.
# profiles = "PROFILE1"

# Binds SIP profile PROFILE1 to this IP address, sets both media profiles to MEDIA1 - accepts a list of profiles.
# profiles = { name = "PROFILE1", media = "MEDIA1" }

[["eth2.81"]]                       # INTERFACE[.VLANID] This is LAN Port and VLAN settings. SBC will create it if it does not exist.
type="static4"                      # The protocol family type and which boot-time protocol should be used. Values are static4, dhcp4, static6, dhcp6, slaac6
address="10.11.1.10/30"             # IP address and network prefix.

"route.SSW1" = { addr = "10.11.1.0/30", via = "10.11.1.9" } # route 3. Static routes through this interface. Format is: "route.name={ addr = destination/prefix, via = gateway }"
"route.SSW2" = { addr = "10.21.1.0/30", via = "10.11.1.9" } # route 4. Static routes through this interface. Format is: "route.name={ addr = destination/prefix, via = gateway }"
"route.CORE" = { addr = "10.11.0.0/16", via = "10.11.1.9" } # route 5. Static routes through this interface. Format is: "route.name={ addr = destination/prefix, via = gateway }"

# [trunks]
# # Binds SIP trunk TRUNK1 to "DOMAIN1" and allows traffic from this domain on ACL named "ACL1"
# "TRUNK1" = { domain = "DOMAIN1", acl = "ACL1" }
#
# # Binds SIP trunk TRUNK2 to "DOMAIN2"
# "TRUNK2" = "DOMAIN2"

# ems = true                        # Use this IP for EMS provisioning ("ip" and "macid" option of EMS section need to be removed)

# Global network settings.

[global]
hostname="ooredoo.local"      # Host Name should be the Fully Qualified Domain Name (FQDN), such as hostname.expample.com.
gw_interface="eth0"           # Default Gateway Interface is the gateway device, such as eth0. Configure this option if you have multiple interfaces on the same subnet, and require one of those interfaces to be the preferred route to the default gateway.
gw_ipv4="10.10.10.1"          # IPV4 address of the network's gateway.
gw_ipv6=""                    # IPV6 address of the network's gateway.
dns1="8.8.8.8"                # Static Name server IP address.
dns2="8.8.4.4"
dns3=""
dns4=""

[options]
max-sessions = 250
sessions-per-sec = 10

# template="mytemplate.tgz"     # Template file to be restored after EMS registration
